version: '3.6'

services:

  angularclient:
    container_name: spaclientprod
    build:
      context: .
      dockerfile: docker/angular-prod.dockerfile
    ports:
      - 8080:80

  dotnetcoreapi:
    container_name: apiprod
    build:
      context: .
      dockerfile: docker/dotnetcore-prod.dockerfile
    ports:
      - 5000:5000

networks:
  default:
      name: app-network
