version: '3.6'

services:

  api-gateway:
    image: reverseproxy
    ports:
      - 80:80

  angularclient:
    image: spaclient:v1

  dotnetcoreapi:
    image: apiserver:v1

networks:
  default:
      name: app-network
