version: '3.6'

services:

  api-gateway:
    container_name: reverseproxy
    build:
      context: .
      dockerfile: docker/nginx/api-gateway-prod.dockerfile
    ports:
      - 80:80

  angularclient:
    container_name: spaclientprod
    build:
      context: .
      dockerfile: docker/angular-prod.dockerfile

  dotnetcoreapi:
    build:
      context: .
      dockerfile: docker/dotnetcore-prod.dockerfile

networks:
  default:
      name: app-network
